name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers On Windows
        if: matrix.os == 'windows-latest'
        run: set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 && yarn add --dev playwright
      - name: Install Playwright Browsers On Mac
        if: matrix.os == 'macos-latest'
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn add --dev playwright
      - name: Build electron app
        run: yarn build
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
