name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    name: Lint and check code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]
      - name: Install dependencies
        run: pnpm install
      - name: Eslint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Typecheck node
        run: pnpm typecheck:node
  unitTests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test:unit
  storybook:
    name: Test storybook
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps chromium
      - name: Build Storybook
        run: pnpm build-storybook --quiet
      - name: Serve Storybook and run tests
        run: pnpm test-storybook:ci
  test:
    name: Test electron app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers On Windows
        if: matrix.os == 'windows-latest'
        run: set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 && pnpm install --save-dev playwright
      - name: Install Playwright Browsers On Mac
        if: matrix.os == 'macos-latest'
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm install --save-dev playwright
      - name: Build electron app
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm test:integration
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30
