name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  storybook:
    name: Test storybook
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm install --save-dev playwright
      - name: Build Storybook
        run: pnpm build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && pnpm test-storybook"
  test:
    name: run e2e tests
    needs: storybook
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm
      - name: Install Playwright Browsers On Windows
        if: matrix.os == 'windows-latest'
        run: set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 && pnpm install --save-dev playwright
      - name: Install Playwright Browsers On Mac
        if: matrix.os == 'macos-latest'
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm install --save-dev playwright
      - name: Build electron app
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
